#!/bin/bash
mkdir -p dollar-loans-app/src/app/'(public)'/how-it-works
mkdir -p dollar-loans-app/src/app/'(public)'/cab-model-explained
mkdir -p dollar-loans-app/src/app/'(public)'/rates-fees
mkdir -p dollar-loans-app/src/app/'(public)'/calculator
mkdir -p dollar-loans-app/src/app/'(public)'/eligibility
mkdir -p dollar-loans-app/src/app/'(public)'/vehicle-value
mkdir -p dollar-loans-app/src/app/'(public)'/faq
mkdir -p dollar-loans-app/src/app/'(public)'/reviews
mkdir -p dollar-loans-app/src/app/'(public)'/about
mkdir -p dollar-loans-app/src/app/'(public)'/contact
mkdir -p dollar-loans-app/src/app/'(public)'/blog
mkdir -p dollar-loans-app/src/app/'(public)'/locations
mkdir -p dollar-loans-app/src/app/'(public)'/careers
mkdir -p dollar-loans-app/src/app/'(public)'/press
mkdir -p dollar-loans-app/src/app/'(public)'/security-trust
mkdir -p dollar-loans-app/src/app/'(public)'/partners
mkdir -p dollar-loans-app/src/app/'(public)'/developers
mkdir -p dollar-loans-app/src/app/'(auth)'/login
mkdir -p dollar-loans-app/src/app/'(auth)'/signup
mkdir -p dollar-loans-app/src/app/'(auth)'/forgot-password
mkdir -p dollar-loans-app/src/app/'(protected)'/dashboard/get-cash
mkdir -p dollar-loans-app/src/app/'(protected)'/dashboard/vehicles
mkdir -p dollar-loans-app/src/app/'(protected)'/dashboard/applications
mkdir -p dollar-loans-app/src/app/'(protected)'/dashboard/agreements
mkdir -p dollar-loans-app/src/app/'(protected)'/dashboard/payments
mkdir -p dollar-loans-app/src/app/'(protected)'/dashboard/documents
mkdir -p dollar-loans-app/src/app/'(protected)'/dashboard/profile
mkdir -p dollar-loans-app/src/app/'(protected)'/dashboard/settings
mkdir -p dollar-loans-app/src/app/'(protected)'/dashboard/support
mkdir -p dollar-loans-app/src/app/'(protected)'/dashboard/referrals
mkdir -p dollar-loans-app/src/app/'(admin)'/admin/applications
mkdir -p dollar-loans-app/src/app/'(admin)'/admin/customers
mkdir -p dollar-loans-app/src/app/'(admin)'/admin/vehicles
mkdir -p dollar-loans-app/src/app/'(admin)'/admin/offers
mkdir -p dollar-loans-app/src/app/'(admin)'/admin/doc-review
mkdir -p dollar-loans-app/src/app/'(admin)'/admin/payments
mkdir -p dollar-loans-app/src/app/'(admin)'/admin/rules
mkdir -p dollar-loans-app/src/app/'(admin)'/admin/audit
mkdir -p dollar-loans-app/src/app/legal/terms
mkdir -p dollar-loans-app/src/app/legal/privacy
mkdir -p dollar-loans-app/src/app/legal/cab-disclosures
mkdir -p dollar-loans-app/src/app/legal/texas-disclosures
mkdir -p dollar-loans-app/src/app/legal/cookies
mkdir -p dollar-loans-app/src/app/legal/complaints
mkdir -p dollar-loans-app/src/app/api/auth
mkdir -p dollar-loans-app/src/app/api/applications
mkdir -p dollar-loans-app/src/app/api/vehicles
mkdir -p dollar-loans-app/src/app/api/payments
mkdir -p dollar-loans-app/src/app/api/documents
mkdir -p dollar-loans-app/src/app/api/partner
mkdir -p dollar-loans-app/src/components/ui
mkdir -p dollar-loans-app/src/components/forms
mkdir -p dollar-loans-app/src/components/layouts
mkdir -p dollar-loans-app/src/components/marketing
mkdir -p dollar-loans-app/src/components/dashboard
mkdir -p dollar-loans-app/src/components/admin
mkdir -p dollar-loans-app/src/lib/db
mkdir -p dollar-loans-app/src/lib/auth
mkdir -p dollar-loans-app/src/lib/validations
mkdir -p dollar-loans-app/src/lib/utils
mkdir -p dollar-loans-app/src/types
mkdir -p dollar-loans-app/src/hooks
mkdir -p dollar-loans-app/public/images/heroes
mkdir -p dollar-loans-app/public/images/marketing
mkdir -p dollar-loans-app/public/images/testimonials
mkdir -p dollar-loans-app/public/images/dashboard
mkdir -p dollar-loans-app/public/images/infographics
mkdir -p dollar-loans-app/public/images/icons
mkdir -p dollar-loans-app/public/images/vehicles
mkdir -p dollar-loans-app/prisma
